# Generated by Django 3.2 on 2021-04-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.CharField(default=None, max_length=250, null=True)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('confirm', 'Confirm'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='new', max_length=20)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
