# Generated by Django 3.2 on 2021-04-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210425_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rejection_reason',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
