# Generated by Django 3.2 on 2021-04-14 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='end_time',
            field=models.CharField(blank=True, default=' ', max_length=20, validators=[django.core.validators.RegexValidator(regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]\\s?(?:AM|PM|am|pm)')]),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='start_time',
            field=models.CharField(blank=True, default=' ', max_length=20, validators=[django.core.validators.RegexValidator(regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]\\s?(?:AM|PM|am|pm)')]),
        ),
    ]
