# Generated by Django 3.2 on 2021-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='specialty_ar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
