# Generated by Django 3.2 on 2021-04-26 11:51

from django.db import migrations


def load_data(apps, schema_editor):
    specialty = apps.get_model("doctors", "Specialty")

    specialty(specialty_en='Nurse', specialty_ar='مُمَرِّض').save()
    specialty(specialty_en='Ophthalmologist', specialty_ar='دكتور عيون').save()
    specialty(specialty_en='Dentist', specialty_ar='طبيب اسنان').save()
    specialty(specialty_en='Otolaryngologist', specialty_ar='طبيب انف اذن حنجرة').save()
    specialty(specialty_en='Neurologist', specialty_ar='طبيب اعصاب').save()
    specialty(specialty_en='Pediatrician', specialty_ar='طبيب اطفال').save()



class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210426_1042'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
